### ISSUE TITLE
EdgeSchema with additional Data

### ISSUE THREAD

**Issue by RlnmnsRimanslim** [roboncode/orango#45]
Is it possible to define an EdgeSchema with additional Data besides _from and _to.
As far as i read your code, if i create an EdgeModel the Data is overwritten (just _from and _to is set). Or do i have to set the additional data after the model is saved?

thanks for your help!

**Comment by aguilera51284** [comment]
Apparently, the 'EdgeSchema' method extends from 'Schema', so I think it would be like that.

```
const orango = require('orango')
let schema = orango.EdgeSchema('User', 'Tweet', {username: { 
  type: String, 
  alphanum: true, min: 3, max: 30, required: 'create'
}})
module.exports = orango.model('Like', schema)

```

https://github.com/roboncode/orango/blob/master/lib/EdgeSchema.js

I think the one who knows the most @roboncode  :smile:

**Comment by RlnmnsRimanslim** [comment]
Thx, that would be great!

**Comment by iraycd** [comment]
@roboncode Can you manage the todo list in https://github.com/roboncode/orango/projects

**Comment by roboncode** [comment]
Yeah, I haven't used that in github before. Thanks for pointing me to it.

**Comment by iraycd** [comment]
@roboncode We have to treat this as a priority. Please add labels to this task.

**Comment by roboncode** [comment]
I fixed the edge to support additional data. Here are the examples I tested with. It is available in release 1.0.0-alpha-1.1.

```js
Like.link("foo", "bar")
Like.link("foo", "bar", { message: 'test1'})
Like.link({_to: 'test/foo', _from: 'test/bar', message: 'test2'})
Like.link({to: 'foo', from: 'bar', message: 'test3'})
Like.link({User: 'foo', Tweet: 'bar', message: 'test4'})
```

I did not add any additional unit tests as part of this fix. The unit tests are in transition to using Jest so many are failing as a result of this. Also since the next release 1.0.0-alpha-2.0 (`orango@next`) has new unit test because of breaking changes I did not feel the need to add any additional tests.

**Comment by iraycd** [comment]
‘’’
Comment.link({_to: 'tweet/sometweet', _from: 'user/userx', message: 'first comment', _key: 'comment1' })


Comment.link({_to: 'comment/comment1', _from: 'user/userx', message: 'nested comment', _key: 'comment2' })

‘’’

This would be a better use case for

**Comment by roboncode** [comment]
@iraycd Thx for the comment and illustration. I just learned something I hadn't considered with Edge Collections. To replicate what you have provided above in Arango, this is what I have...

![image](https://user-images.githubusercontent.com/820723/50537690-584fe200-0b20-11e9-8ded-0c3036496e69.png)

And the records would look like this in the `comments` collection...

![image](https://user-images.githubusercontent.com/820723/50537840-bd0c3c00-0b22-11e9-9393-830ba290768f.png)

I am working on link / unlink in [orango@next](https://github.com/roboncode/orango/tree/next) and want to make sure I understand correctly.

Let me know if this looks correct. Thx Rob

**Comment by iraycd** [comment]
That’s great. 
Loved the approach.

But it won’t be backward compatible if Edge is being removed. That won’t  be a problem, as there are not many orango developers.

**Comment by roboncode** [comment]
Right. I am not concerned with backwards compatibility (yet) - since it is alpha. Things change, especially as people start to use it and I discover ways that others are using it that I had not considered because it isn't part of my workflow. After this next release (Alpha 2) I feel like the API will be in a good and stable state. Feedback is always helpful. I have already started migrating to Alpha 2 in a production application and feel like the workflow is much better and easier to debug.

**Comment by roboncode** [comment]
This issue is being marked as resolved. Also it works in  orango@next with the aforementioned changes. Examples can be found for orango next in the next branch

```js
npm i orango@next
```

The API has undergone many breaking changes so be sure to review examples - https://github.com/roboncode/orango/tree/next/examples
